# User Configuration for ${keyboard.name}

CONFIG_ZMK_POINTING=y

# Enable NFC pins as GPIOs
#CONFIG_NFCT_PINS_AS_GPIOS=y

# The pinnacle driver also requires this to include sleep code
CONFIG_ZMK_MOUSE=y

CONFIG_I2C=y
CONFIG_INPUT=y
CONFIG_INPUT_PINNACLE=y
