manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
        exclude:
          - zephyr/dts/bindings/input/cirque,pinnacle-spi.yaml
          - zephyr/dts/bindings/input/cirque,pinnacle-i2c.yaml
    - name: cirque-input-module
      remote: petejohanson
      revision: main
  self:
    path: config
