manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import:
        file: app/west.yml
        # Try blocklisting 'zmk's version of the input module specifically
        name-blocklist:
          - zmk-input-module 
          - cirque
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      path: modules/input/cirque
  self:
    path: config
